### ISSUE TITLE
`localValidityPeriodHours` is not used

### ISSUE THREAD

**Issue by tcrasset** [pulumi/pulumi-tls-self-signed-cert#1]
### What happened?

While trying to create a certificate and encountering an error (for another issue), I went through the source code and noticed that `localValidityPeriodHours` is not used after passing it as argument in the `SelfSignedCertificate` constructor in [selfSignedCert.ts](https://github.com/pulumi/pulumi-tls-self-signed-cert/blob/main/provider/cmd/pulumi-resource-tls-self-signed-cert/selfSignedCert.ts).

### Steps to reproduce

Go through the source code of [selfSignedCert.ts](https://github.com/pulumi/pulumi-tls-self-signed-cert/blob/main/provider/cmd/pulumi-resource-tls-self-signed-cert/selfSignedCert.ts).

### Expected Behavior

I expected `localValidityPeriodHours` to be passed as argument for `validityPeriodHours` in `tls.LocallySignedCert` or in `tls.SelfSignedCert`

### Actual Behavior

`localValidityPeriodHours` is used nowhere.

### Output of `pulumi about`

```
Dependencies:
NAME                          VERSION
prettier                      2.7.1
@pulumi/command               0.5.2
@pulumi/gcp                   6.37.0
@pulumi/kubernetes            3.21.2
@pulumi/pulumi                3.40.1
@pulumi/tls-self-signed-cert  0.0.3
@types/node                   14.18.29

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by zchase** [comment]
@tcrasset Thanks for filing the issue! We will take a look and get this fixed up for ya.

**Comment by zchase** [comment]
@tcrasset This should be addressed in https://github.com/pulumi/pulumi-tls-self-signed-cert/pull/3 and is now available in the latest release. Thanks!
